# Generated by Django 3.0.5 on 2020-04-15 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200414_1343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planning',
            old_name='date_end',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='planning',
            old_name='date_start',
            new_name='start',
        ),
    ]
